# Generated by Django 2.2.12 on 2020-04-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='summary',
        ),
    ]
