# Generated by Django 2.2.12 on 2020-04-29 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobs_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
